



export default function Shop() {
    return (
        <div class="bg-orange-500">
            <h1>Home</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean efficitur diam quis efficitur pellentesque. Duis fermentum viverra metus, eget pharetra sem accumsan vel. In sit amet leo a nisl interdum tempus at at metus. Nulla pulvinar enim felis, non eleifend nisi varius ut. Nam ipsum lorem, ullamcorper ultricies tortor sit amet, consequat ultrices justo. Pellentesque turpis purus, luctus ut sodales at, rhoncus ac urna. Integer facilisis imperdiet eros id consequat. Etiam facilisis, tellus sed gravida laoreet, orci nibh blandit urna, id mollis orci augue eu erat. Sed venenatis, velit vitae posuere bibendum, odio lectus porta metus, sit amet interdum libero tellus a magna. Mauris quis sapien in enim rhoncus volutpat et et ipsum. Nunc eu lectus vel ligula pretium lobortis quis sit amet velit. Nullam iaculis at diam id rhoncus. Phasellus sem purus, rhoncus ac est ut, vulputate consectetur mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at metus elit.

Nulla metus risus, tempor at malesuada ut, aliquam vel nibh. Integer ut bibendum sapien. Maecenas eget feugiat velit, eget facilisis lacus. Vivamus non sapien at diam pretium fringilla eu vel lorem. Donec aliquam ac lacus non cursus. Etiam quis quam vel purus lobortis tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus at molestie ex. Mauris non mi sollicitudin nisi hendrerit ultrices. Praesent ut elit nec sem mattis fringilla nec sed lectus. Suspendisse efficitur odio lectus. Aliquam erat volutpat. Sed imperdiet ante vitae porta maximus.

Fusce semper magna id quam commodo pellentesque. Suspendisse a ultricies risus. Phasellus sed nisl a eros volutpat facilisis a quis velit. Duis eget massa eros. Quisque pulvinar tempus est id luctus. Sed varius accumsan finibus. Vestibulum suscipit pretium arcu.

Proin interdum urna sed hendrerit dictum. Fusce sed mauris eget libero interdum aliquet a nec magna. Curabitur felis tellus, euismod eu bibendum in, mollis et turpis. Morbi viverra, leo quis rhoncus imperdiet, lectus urna molestie leo, at posuere erat justo vitae justo. Nam ac metus a ante luctus fermentum quis ac tellus. Nullam eleifend at velit in volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam sit amet posuere magna. Suspendisse sit amet urna quis ex maximus posuere id vitae tellus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed tempor ullamcorper quam, auctor aliquam magna dictum id. Nulla vel metus quam. Curabitur tristique magna quis lacus sagittis, quis finibus leo finibus. Curabitur nisl velit, accumsan quis arcu eu, tempor condimentum est.

Nullam vel dolor gravida, blandit turpis vel, rutrum mauris. Nam quis mattis neque, quis congue sapien. Quisque ligula sem, consectetur sed ex at, consequat lobortis nunc. Pellentesque tellus neque, cursus at dapibus id, tincidunt nec nisl. Nullam quis vestibulum sapien. Morbi feugiat, nisl non vehicula tempus, massa diam lacinia est, nec viverra dolor dolor non nisl. Etiam luctus in nunc non fringilla. Sed consequat augue ex, semper posuere justo tristique et. Phasellus facilisis euismod velit, at dictum ligula lobortis eu. Etiam ultrices hendrerit quam, quis pellentesque tellus.

Integer sit amet commodo ex, eget elementum mauris. Integer est turpis, porta nec aliquam sit amet, malesuada nec purus. Proin semper tortor nisi, at placerat justo interdum sagittis. Integer vehicula orci non sapien vehicula dictum. Phasellus id porttitor justo. Pellentesque malesuada eros eu elit porttitor rutrum. Morbi sed sapien vitae elit rutrum egestas egestas vel magna. Donec molestie tristique vestibulum. Ut scelerisque dolor in tortor posuere, at pulvinar dolor facilisis. Vestibulum et rhoncus dui. Sed a urna vitae felis porta sagittis. Phasellus nec volutpat purus, rhoncus tristique urna. Etiam sollicitudin viverra cursus.

Nam id tellus finibus ex lobortis vestibulum. Nam vel consequat enim. Curabitur tristique nunc ac ex commodo finibus. Nunc sodales tellus velit, eget auctor ex tincidunt a. Nam tempor ornare leo. Cras ultrices purus id enim tincidunt, quis ornare dui sodales. Donec et arcu ornare tellus laoreet ultrices. Nulla facilisi. Nulla auctor massa risus, a rhoncus lacus ultrices non. Nulla facilisi. Aliquam ornare urna volutpat ipsum placerat, a molestie magna pellentesque. Cras maximus libero dui, eu placerat nulla tincidunt dignissim.

Ut tempus, urna vel suscipit pretium, massa orci elementum risus, rhoncus auctor mauris felis commodo lorem. Praesent in cursus ipsum, et pharetra mauris. Fusce rutrum tortor ac magna aliquam feugiat. Sed arcu massa, dapibus vel auctor vel, placerat id erat. Nunc tristique feugiat tellus et volutpat. Cras faucibus interdum nibh convallis vehicula. Praesent ornare arcu odio, at dictum elit egestas eget. Vestibulum eu semper dui. Cras lacinia rutrum ex, eu pulvinar elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Sed pellentesque finibus neque, eu volutpat felis posuere vitae. Suspendisse vestibulum vulputate justo, quis placerat quam porttitor et. Integer ornare porttitor est, sed eleifend odio sagittis nec. Pellentesque ut eleifend velit. Nulla et luctus leo, a luctus massa. Pellentesque commodo ante sed congue blandit. Phasellus dapibus lacus et lectus rhoncus elementum. Sed tincidunt eget metus vitae suscipit.

Aenean vel bibendum risus. Quisque lorem arcu, porttitor ut erat eu, porta ultricies enim. Mauris quis odio condimentum erat iaculis mollis eu vitae lorem. Nulla non felis nisi. Nam non nisl ac erat cursus vestibulum. In quis maximus nibh. Nullam pulvinar pellentesque augue, vitae feugiat dolor euismod nec. Etiam lobortis tortor vitae libero varius volutpat. Vivamus tempor ornare urna non ultrices. Duis accumsan nibh a ante tristique consequat. Proin eu porttitor sapien, a vulputate risus. Proin tempor feugiat dui nec laoreet. Maecenas bibendum lectus sit amet arcu feugiat, non volutpat neque lobortis. Suspendisse potenti. Nunc nec augue arcu. Curabitur mattis orci sit amet auctor elementum.</p>
        </div>
    );
}